# Generated by Django 5.1.4 on 2025-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_borrowpoint_approved_alter_borrowpoint_fully_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='points_were',
            field=models.CharField(choices=[('earned', 'earned'), ('redeemed', 'redeemed'), ('loaned', 'loaned'), ('borrowed', 'borrowed'), ('repayment of  borrowed points', 'repayment of  borrowed points')], default='earned', help_text=' purpose for the points', max_length=100),
        ),
        migrations.AlterField(
            model_name='loyaltypointscategory',
            name='category',
            field=models.CharField(choices=[('points on purchases made', 'points on purchases made'), ('signup points', 'signup points'), ('points on visiting the store', 'points on visiting the store'), ('points from refferal sales', 'points from refferal sales'), ('points on bringing friends to the store', 'points on bringing friends to the store'), ('redeemed', 'redeemed'), ('loaned', 'loaned'), ('borrowed', 'borrowed'), ('repayment of  borrowed points', 'repayment of borrowed points')], max_length=100),
        ),
    ]
