# Generated by Django 5.1.4 on 2025-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0004_alter_loyaltypointscategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltypointscategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("points on purchases made", "points on purchases made"),
                    ("signup points", "signup points"),
                    (
                        "points for joining a challenge",
                        "points for joining a challenge",
                    ),
                    (
                        "points spent for votes purchase",
                        "points spent for votes purchase",
                    ),
                    ("points on visiting the store", "points on visiting the store"),
                    ("points from refferal sales", "points from refferal sales"),
                    (
                        "points on bringing friends to the store",
                        "points on bringing friends to the store",
                    ),
                    ("redeemed", "redeemed"),
                    ("loaned", "loaned"),
                    ("borrowed", "borrowed"),
                    ("repayment of  borrowed points", "repayment of borrowed points"),
                ],
                max_length=100,
            ),
        ),
    ]
