# Generated by Django 5.1.4 on 2025-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productname_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gas-images'),
        ),
    ]
