# Generated by Django 5.1.4 on 2025-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productname_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='second_image',
            field=models.ImageField(blank=True, help_text='for 13kg gas', null=True, upload_to='gas-images'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='image',
            field=models.ImageField(blank=True, help_text='for 6kg gas', null=True, upload_to='gas-images'),
        ),
    ]
