# Generated by Django 5.1.4 on 2025-04-22 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('country', models.CharField(default='Kenya', max_length=250)),
                ('county', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('ward', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, help_text='describe what you do')),
                ('subscription_plan', models.CharField(blank=True, max_length=250)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ManyToManyField(blank=True, to='customers.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
