# Generated by Django 5.1.4 on 2025-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="total_loyalty_points",
            field=models.IntegerField(default=0),
        ),
    ]
