# Generated by Django 5.1.4 on 2025-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_business_total_loyalty_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="c",
            field=models.URLField(blank=True, null=True),
        ),
    ]
