# Generated by Django 5.1.4 on 2025-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="total_available_votes",
            field=models.IntegerField(
                default=0,
                help_text="this are vote slots that will be used to cast votes for others",
            ),
        ),
    ]
