# Generated by Django 5.1.4 on 2025-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_total_available_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="total_available_votes",
            field=models.IntegerField(
                default=10,
                help_text="this are vote slots that will be used to cast votes for others",
            ),
        ),
    ]
