# Generated by Django 5.1.4 on 2025-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customer_total_available_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
