# Generated by Django 5.1.4 on 2025-06-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_customer_profile_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="profile_image_url",
            new_name="profile_image_id",
        ),
    ]
