# Generated by Django 5.1.4 on 2025-06-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_rename_profile_image_url_customer_profile_image_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="profile_image_id",
            new_name="profile_image_url",
        ),
    ]
