# Generated by Django 5.1.4 on 2025-06-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("customers", "0003_customer_date_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefferalChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("today", "today"),
                            ("this week", "this week"),
                            ("this month", "this month"),
                            ("this year", "this year"),
                            ("upto date", "upto date"),
                        ],
                        max_length=100,
                    ),
                ),
                ("challenge_name", models.CharField(max_length=200)),
                (
                    "participating_reward",
                    models.IntegerField(
                        default=0,
                        help_text="points awarded to customers for participating",
                    ),
                ),
                (
                    "challenge_reward",
                    models.CharField(
                        help_text="whats the reward for the challenge", max_length=500
                    ),
                ),
                (
                    "target_winners",
                    models.IntegerField(
                        help_text="how many winners do you want for this challenge"
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="businesses.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefferalChallengeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_refferals", models.IntegerField(default=0)),
                (
                    "received_reward",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("updated_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.refferalchallenge",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
