# Generated by Django 5.1.4 on 2025-06-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("challenges", "0001_initial"),
        ("customers", "0004_customer_total_available_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="refferalchallenge",
            name="challenge_brief",
            field=models.TextField(
                blank=True,
                help_text="share a brief about the challenge",
                max_length=1500,
            ),
        ),
        migrations.AlterField(
            model_name="refferalchallengeresult",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refferal_challenges",
                to="challenges.refferalchallenge",
            ),
        ),
        migrations.CreateModel(
            name="VoteChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge_name", models.CharField(max_length=200)),
                (
                    "participating_reward",
                    models.IntegerField(
                        default=0,
                        help_text="points awarded to customers for participating",
                    ),
                ),
                (
                    "challenge_reward",
                    models.CharField(
                        help_text="whats the reward for the challenge", max_length=500
                    ),
                ),
                (
                    "challenge_brief",
                    models.TextField(
                        blank=True,
                        help_text="share a brief about the challenge",
                        max_length=1500,
                    ),
                ),
                (
                    "target_winners",
                    models.IntegerField(
                        help_text="how many winners do you want for this challenge"
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField()),
                (
                    "challenge_owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="one who creates the challenge and responsible for distributing rewards",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_owner",
                        to="businesses.business",
                    ),
                ),
                (
                    "challenge_patners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="business patners",
                        related_name="challenge_patners",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="businesses.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteChallengeParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_voters", models.IntegerField(default=0)),
                ("total_votes", models.IntegerField(default=0)),
                (
                    "received_reward",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_challenges",
                        to="challenges.votechallenge",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_votes", models.IntegerField(default=0)),
                ("date_voted", models.DateField(auto_now_add=True)),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "challenge_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_participant",
                        to="challenges.votechallengeparticipant",
                    ),
                ),
            ],
        ),
    ]
