# Generated by Django 5.1.4 on 2025-06-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_refferalchallenge_challenge_brief_and_more"),
        ("customers", "0004_customer_total_available_votes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChallengeVote",
            new_name="Vote",
        ),
    ]
