# Generated by Django 5.1.4 on 2025-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_rename_challengevote_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="refferalchallenge",
            name="challenge_guidelines",
            field=models.TextField(
                blank=True,
                help_text="share a brief about the challenge",
                max_length=1500,
            ),
        ),
        migrations.AddField(
            model_name="refferalchallenge",
            name="challenge_reward_monetary_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="votechallenge",
            name="challenge_guidelines",
            field=models.TextField(
                blank=True,
                help_text="share a brief about the challenge",
                max_length=1500,
            ),
        ),
        migrations.AddField(
            model_name="votechallenge",
            name="challenge_reward_monetary_value",
            field=models.IntegerField(default=0),
        ),
    ]
