# Generated by Django 5.1.4 on 2025-06-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_refferalchallenge_challenge_guidelines_and_more"),
        ("customers", "0005_alter_customer_total_available_votes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteChallengePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("date_invited", models.DateField(auto_now_add=True)),
                ("date_accepted", models.DateField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_challenges_patners",
                        to="challenges.votechallenge",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
