# Generated by Django 5.1.4 on 2025-06-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_business_total_loyalty_points"),
        ("challenges", "0005_votechallengepartner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votechallengepartner",
            name="date_accepted",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="votechallengepartner",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="businesses.business"
            ),
        ),
    ]
