# Generated by Django 5.1.4 on 2025-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_alter_votechallengepartner_date_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votechallenge",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="votechallenge",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
