# Generated by Django 5.1.4 on 2025-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_alter_votechallenge_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refferalchallenge",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="refferalchallenge",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
